# Fokussierte Modbus-Register-Map: nur relevante Werte für Wallbox und Energiefluss.
# Vollständige Map (80+ Register) liegt im Legacy-Repo unter modbus_map.py.

SENSOR_DEFINITIONS = {
    # --- Smartmeter: Netzleistung gesamt ---
    0: {
        "name": "Active Power+",
        "obis": "1-0:1.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    2: {
        "name": "Active Power-",
        "obis": "1-0:2.4.0*255",
        "unit": "W",
        "scale": 0.1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    26: {
        "name": "Supply Frequency",
        "obis": "1-0:14.4.0*255",
        "unit": "Hz",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "frequency",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    # --- Smartmeter: Energiezähler gesamt ---
    512: {
        "name": "Active energy+",
        "obis": "1-0:1.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device_class": "energy",
        "state_class": "total_increasing",
        "device": "smartmeter",
    },
    516: {
        "name": "Active energy-",
        "obis": "1-0:2.8.0*255",
        "unit": "Wh",
        "scale": 0.1,
        "type": "uint64",
        "device_class": "energy",
        "state_class": "total_increasing",
        "device": "smartmeter",
    },
    # --- Energiefluss-Übersicht (KOSTAL-spezifische Register ab 40972) ---
    40972: {
        "name": "Grid power Total",
        "unit": "W",
        "scale": 1,
        "type": "int32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40974: {
        "name": "Sum output inverter AC",
        "unit": "W",
        "scale": 1,
        "type": "int32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40976: {
        "name": "Sum pv power inverter DC",
        "unit": "W",
        "scale": 1,
        "type": "int32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40982: {
        "name": "Home consumption",
        "unit": "W",
        "scale": 1,
        "type": "int32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40984: {
        "name": "Sum battery charge/discharge DC",
        "unit": "W",
        "scale": 1,
        "type": "int32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40986: {
        "name": "System state of charge",
        "unit": "%",
        "scale": 1,
        "type": "uint16",
        "device_class": "battery",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40988: {
        "name": "Home consumption from PV",
        "unit": "W",
        "scale": 1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40990: {
        "name": "Home consumption from battery",
        "unit": "W",
        "scale": 1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40992: {
        "name": "Home consumption from grid",
        "unit": "W",
        "scale": 1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40996: {
        "name": "Sum wallbox charge power total",
        "unit": "W",
        "scale": 1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    40998: {
        "name": "Sum wallbox charge power PV",
        "unit": "W",
        "scale": 1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    41000: {
        "name": "Sum wallbox charge power battery",
        "unit": "W",
        "scale": 1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    41002: {
        "name": "Sum wallbox charge power grid",
        "unit": "W",
        "scale": 1,
        "type": "uint32",
        "device_class": "power",
        "state_class": "measurement",
        "device": "smartmeter",
    },
    # --- Wallbox Live-Werte ---
    49206: {
        "name": "Enector_status",
        "unit": "",
        "scale": 1,
        "type": "uint64",
        "device_class": "enum",
        "state_class": None,
        "device": "wallbox",
        "map": {
            0: "Unbekannt",
            1: "Offline",
            2: "Verbunden",
            3: "Pausiert",
            4: "Probing",
            5: "Ladend",
            6: "Kommunikationsfehler",
            7: "Service Mode",
        },
    },
    49218: {
        "name": "Enector_L1",
        "unit": "A",
        "scale": 0.001,
        "type": "uint32",
        "device_class": "current",
        "state_class": "measurement",
        "device": "wallbox",
    },
    49246: {
        "name": "Enector_Ladeleistung",
        "unit": "W",
        "scale": 0.001,
        "type": "uint64",
        "device_class": "power",
        "state_class": "measurement",
        "device": "wallbox",
    },
    49254: {
        "name": "Enector_geladene_Energie",
        "unit": "Wh",
        "scale": 0.001,
        "type": "uint64",
        "device_class": "energy",
        "state_class": "total_increasing",
        "device": "wallbox",
    },
}
